name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: |
        g++ main.cc
        ./a.exe
    - name: sign
      run:
        ssigncode.exe vsign -s https://vsign.trustasia.com --cert_from csign -u ${{ vars.OPERATOR_HASH }} --cert_hash  ${{ vars.CERT_HASH }} -i a.exe -o ./a-signed.exe
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4.4.3
      with:
          name: artifact
          path: |
            ./a.exe
            ./a-signed.exe
